name: CI

on:
  push:
    # tags:
    #   - '*'
    branches:
      - 'feature/*'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
          git clone https://github.com/estesp/manifest-tool && cd manifest-tool && git checkout v0.9.0 && sudo make && sudo make install && cd .. && rm -Rf manifest-tool
          docker run --rm --privileged multiarch/qemu-user-static:register
          sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u Bruce17 --password-stdin docker.pkg.github.com
      - name: Build image
        run: make build
      - name: Publish image
        run: make publish latest
